import type { AtlasItem } from "./types"

export const sampleItems: AtlasItem[] = [
  {
    slug: "umap-notes",
    title: "UMAP Notes",
    type: "field_note",
    date: "2023-05-02",
    desc: "Quick notes on UMAP parameters",
    tags: ["umap", "embeddings"],
    topics: ["Dimensionality Reduction"],
    status: "uncharted",
    x: 0.9898078310610705,
    y: -1,
    cluster: 0,
  },
  {
    slug: "atlas-overview",
    title: "Atlas Overview",
    type: "map",
    date: "2023-06-01",
    desc: "The map of maps",
    tags: ["overview"],
    topics: ["Atlas", "Meta"],
    status: "charted",
    x: -0.767276854696059,
    y: -0.7042090176641949,
    cluster: 1,
  },
  {
    slug: "altair-express",
    title: "Altair Express",
    type: "project",
    date: "2023-01-01",
    desc: "Instrumental Interaction Operators for Data Analysis",
    tags: ["instrumental interaction", "altair", "prototyping"],
    topics: ["Interaction", "Data Visualization"],
    status: "charted",
    thumbnail: "./images/alx/thumbnail.png",
    alt: "apple and shaking hands",
    repo_url: "https://github.com/dwootton/altair-express",
    x: 1,
    y: -0.9308807824916734,
    cluster: 0,
  },
  {
    slug: "arctic-explorer",
    title: "Arctic Explorer",
    type: "project",
    date: "2022-11-05",
    desc: "A polar data explorer with narrative routes",
    tags: ["maps", "deck.gl", "antarctic"],
    topics: ["Mapping", "Data Visualization"],
    status: "in_progress",
    live_url: "https://example.com/arctic-explorer",
    x: 0.4178542408318655,
    y: 0.9457440324315609,
    cluster: 0,
  },
  {
    slug: "analysis-operators",
    title: "Analysis Operators",
    type: "route",
    date: "2023-03-12",
    desc: "A route exploring operators for sensemaking",
    tags: ["operators", "sensemaking"],
    topics: ["Interaction", "HCI"],
    status: "charted",
    related: ["altair-express"],
    x: 0.2852442772600554,
    y: -0.2850678785921179,
    cluster: 0,
  },
  {
    slug: "interaction-palette",
    title: "Interaction Palette",
    type: "waypoint",
    date: "2023-04-10",
    desc: "A compact palette for frequent actions",
    tags: ["shortcuts", "ui"],
    topics: ["Interaction"],
    status: "in_progress",
    related: ["altair-express", "analysis-operators"],
    x: -1,
    y: 1,
    cluster: 1,
  },
]
